language: python
python:
    - '2.7'
    - '3.5'
install:
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
          wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"

    - conda config --set always_yes yes --set changeps1 no
    - conda create -n travis python=$TRAVIS_PYTHON_VERSION
    - conda env update -n travis -f conda/dev-environment.yml
    - source activate travis

    - pip install --upgrade pytest coverage codecov
    - pip install -r requirements.txt
script:
    - coverage run --source dmpr -m py.test
after_success:
    - codecov
# deploy:
#   provider: pypi
#   user:
#   password:
#     secure: 
#   on:
#     tags: true
#     repo: ScottWales/dmpr
#   distributions: "sdist bdist_wheel"
addons:
    code_climate:
        repo_token:
            secure: "obwQt15s2ALweyEkbfT+QCDtxRw4juO/G3SV2b2at7wOf2zFooaf6LEW5lxu32ls9p7jdLXl6thiibvKc6HyJLQyS2wHZ6vgilGZHD+g5q+Um8FKMPC11JI5u3j1HSVkKKvgPHWjPA6MGGiSZc11DY/MCIvuNJOjR5735PnQk2Ff4C19k5kAVV0J+XPW5gFaIatDSI1PkBfknLrn7JgHKoohvfCmBpzfAqbk3vxRJnFX9iRcnkk86vm/YEKAmXeDllDFXiOTBZnrY4a6hFY4YFJ96SKayiKxwd3QAbqWE+/ZieGLrd/1clAvTlFTpusqIGFVrn5uvioot2tXytdmOqmiIB8pSzFOvfeELT4K5oh2rHn65mS5LEOd6scy6+RM2uD74sDrYlJBMZd1h6rp1y83foMoQw4qR2AKZ9QjMFh87yK9r6/mfN9GwcmjqtAwCLLe+GrdnE8QRmO5cFzV4PnrP7B4fOtCOTEUtmCoMnQvK2QO1cDM8rqLlF7eqwS9Dy9UctdeydqnABCwHBWOxIzYuxkbnDLLM9BrpB8x+L6XhClh8Agk4HJOpWU0zvCfVxb5oPvU/agK2mckWEWoEMr7NvSrhw1aU2VfGldGAoV/+nmx2eB0hVhPuwYCSeYiP+m2SMsfP0jIC3sSz2mH+OIIkZ1vnJzMZ9RKFy4X+FI="
